### ISSUE TITLE
Outdated server version warning

### ISSUE THREAD

**Issue by scuty2000** [bigscience-workshop/petals#201]
- Add a warning message when starting a petals server if the version used is outdated.
  - This should prevent servers from joining the swarm when they are not up-to-date.

**BONUS:** also warn currently running servers about a new update, and ban them after a defined grace period if the update has not been performed.

**Comment by borzunov** [comment]
Thanks for the suggestion!

I have implemented this in #209. Servers now report their version in `rpc_info()`, which would allow clients to check the server's versions in future.
