### ISSUE TITLE
try bloomz in chat.petals.ml

### ISSUE THREAD

**Issue by justheuristic** [bigscience-workshop/petals#207]
There are [rumors](https://www.reddit.com/r/MachineLearning/comments/zstequ/d_when_chatgpt_stops_being_free_run_sota_llm_in/) that [bloomz](https://huggingface.co/bigscience/bloomz) makes for a far closer approximation of intruct/chatGPT than the original bloom. Let's see how it works with chat.petals!

Steps:

1. convert the model to petals format, [like this](https://github.com/bigscience-workshop/petals/blob/main/.github/workflows/run-tests.yaml#L40-L42), upload to yourname/bloomz-petals
   - conversion script requires 400gb ram (can be optimized)
2. run some petals servers with the new model:
   - `python -m petals.cli.run_server yourname/bloomz-petals`
3. run a version of chat.petals with the new model
   - take https://github.com/borzunov/chat.petals.ml 
   - change [this line](https://github.com/borzunov/chat.petals.ml/blob/main/app.py#L14) to your model name
   - (optional) you may want to change prompts to better fit the model's original role
4. let contributors play with it

Note: since we don't have active volunteers for the model (yet!), i can help you find some gpus to bootstrap the model

**Comment by borzunov** [comment]
I'll launch the conversion now. At least 3 people in Discord are interested in running BLOOMZ and seem to be ready to connect some servers.

**Comment by tijszwinkels** [comment]
This one can be closed, right?

**Comment by borzunov** [comment]
Done.
