### ISSUE TITLE
Specify minimal requirements to GPU's for contributing

### ISSUE THREAD

**Issue by Joemgu7** [bigscience-workshop/petals#222]
I tried to contribute to the Swarm using an 8gb card and then quickly realized, even when setting the Pytorch fragmeneted split size to 512mb that I could not use this card to contribute to inference. It would be nice to have a section in the readme that specifies this.

**Comment by justheuristic** [comment]
To the best of my knowledge, it should be possible to serve one BLOOM block using a 8GB card - or at least that's how it was last summer. You may need to reduce max cache size in options.

Q1: did you run the server via `python -m petals.cli.run_server bigscience/bloom-petals` or did you add some extra options?

Q2: what cuda capability do you have? Please check with
```python -c 'import torch; print(torch.cuda.get_device_capability("cuda:0"))'```

p.s. if we lost compatibility with 8gb cards, then I agree that it would be great to specify that in the readme.

**Comment by Joemgu7** [comment]
NVM, tried it out this morning and it seems to be working fine. No clue what happened there. Compute Capability is 6.1 (gtx 1070), using docker image on manjaro kernel 6.1.1

**Comment by borzunov** [comment]
It's possible that you had something else running on your GPU when you tried to run the server for the first time, so much less than 8 GB was available.
