### ISSUE TITLE
Private swarm don't work for me

### ISSUE THREAD

**Issue by upwindflys** [bigscience-workshop/petals#256]
Hello all,

I launch my own swarm (not public IPs) according to [Launch-your-own-swarm](https://github.com/bigscience-workshop/petals/wiki/Launch-your-own-swarm) .
Each computer has 1 gpu and 40GB memory, and contains 15 blocks of petals-7b1-bloom.

The server seems to be working normally
But when i do inference by setting 'initial_peers=$MY OWN SWARM', an error occured.

![image](https://user-images.githubusercontent.com/16665352/218015607-07dfdafd-7e0c-4b21-8bad-4f57e82bc75e.png)

Does anyone know what the possible reason is？

**Comment by borzunov** [comment]
Hi @upwindflys,

Sorry for the delayed response. I have not seen the issue you're reporting before.

If it's still relevant, could you please send the full commands you use for running the servers, so we can try reproducing the issue?

**Comment by upwindflys** [comment]
@borzunov hi, when starting the server, i tried to change the parameter 'compression' from 'BLOCKWISE_8BIT' to 'None', which solves the problem for me, but I don't know why it works. 
In the mean while, it seems that the value of parameter 'compression' are recommended 'None' according to [Launch-your-own-swarm](https://github.com/bigscience-workshop/petals/wiki/Launch-your-own-swarm)

**Comment by borzunov** [comment]
Got it. Note that servers now choose best values for most arguments (including `--compression`) automatically, you don't have to specify them manually anymore. I've recently updated the "Launch your own swarm" guide to reflect this.

I'll close this issue for now, but feel free to reopen it or create a new one if you meet any new issues.
