### ISSUE TITLE
How to start a monitor for the private swarm?

### ISSUE THREAD

**Issue by xu-song** [bigscience-workshop/petals#258]

**Comment by upwindflys** [comment]
Refer to this. [https://github.com/borzunov/health.petals.ml](url)

**Comment by borzunov** [comment]
@xu-song,

Please use the code from [this repo](https://github.com/borzunov/health.petals.ml), as @upwindflys suggested.

I have just added readme sections that explain how to run the app and monitor your private swarm instead of the public one.

Don't hesitate to reach out if you meet any issues.

**Comment by borzunov** [comment]
Closing this since the question has been answered (hopefully). Feel free to reopen if you'd like to continue the discussion.
