### ISSUE TITLE
Finetuning with my own swarm

### ISSUE THREAD

**Issue by Ted-developer** [bigscience-workshop/petals#261]
I have already setting up my own private swarm. I want to use it do [prompt-tuning-personachat](https://github.com/bigscience-workshop/petals/blob/main/examples/prompt-tuning-personachat.ipynb).  

I don't how to do it, I appreciate you help

**Comment by borzunov** [comment]
Hi @Ted-developer!

You need to specify your swarm's initial peers when you create the model:

```python
model = DistributedBloomForCausalLM.from_pretrained(
    MODEL_NAME,
    pre_seq_len=NUM_PREFIX_TOKENS, 
    tuning_mode=TUNING_MODE,
    initial_peers=["/ip4/1.2.3.4/tcp/1234/p2p/Qm...", "/ip4/1.2.3.5/tcp/1235/p2p/Qm..."],
).to(DEVICE)
```

**Comment by Ted-developer** [comment]
It works, thanks a lot
