### ISSUE TITLE
Error when I use private swarm for finetuning with personachat example

### ISSUE THREAD

**Issue by Ted-developer** [bigscience-workshop/petals#262]
I have already setting up my own private swarm. I want to use it do [prompt-tuning-personachat](https://github.com/bigscience-workshop/petals/blob/main/examples/prompt-tuning-personachat.ipynb).

Model : bigscience/bloom-7b1-petals

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/89832629/219829144-d33c138b-85aa-4f14-bbdf-16ceee0f3108.png">

but the swarm work well for inference case

<img width="862" alt="image" src="https://user-images.githubusercontent.com/89832629/219829194-99918162-8c99-43d3-a8c3-493948edeb88.png">

and the gpu server log

<img width="741" alt="image" src="https://user-images.githubusercontent.com/89832629/219829223-5a2b3ab5-258e-4714-874a-47be44604879.png">

I have check the model mayby not match, but in trian script and server use script they are both  bigscience/bloom-7b1-petals

I appreciate you help, thank you very much

**Comment by borzunov** [comment]
Hi @Ted-developer,

Have you been able to fix this error? If yes, what was the reason?
