### ISSUE TITLE
Bloom-176b

### ISSUE THREAD

**Issue by teokono** [bigscience-workshop/petals#269]
разберитесь с тем, как генерировать ей текст.

**Comment by borzunov** [comment]
Hi @teokono,

Please write in English, so everyone from our community can read this issue and participate.

We provide instructions for generating text in our [main tutorial](https://colab.research.google.com/drive/1Ervk6HPNS6AYVr3xVdQnY5a-TjjmLCdQ?usp=sharing). If you have any issues with running it, please let us know.

I'll close this issue for now, but feel free to reopen it if you need help with anything.
