### ISSUE TITLE
I get warning when running example of petals

### ISSUE THREAD

**Issue by Luoyang144** [bigscience-workshop/petals#281]
Hello，I'm tring to run example in this [link](https://github.com/bigscience-workshop/petals/blob/main/examples/prompt-tuning-personachat.ipynb), and get warning like this:
`[WARN] [petals.client.sequential_autograd.sequential_forward:101] Caught exception when running forward via RemoteSpanInfo(start=0, end=1, peer_id=<libp2p.peer.id.ID (12D3KooWDEn4cZqinPtobwxjynMpUgEzxEAiaCQ2BRbcMp7fP3es)>) (retry in 0 sec): TimeoutError()`
Can I ignore this error and what are the consequences of this?

**Comment by borzunov** [comment]
Hi @Luoyang144,

This warning is caused by a faulty server, and the client should repeat the request to another server shortly. If your training run proceeds correctly, you can ignore this warning.

**Comment by borzunov** [comment]
This should not affect your training.

I'd like to clarify, what do you mean by "I'm using HPC for training"? Have you set up your own private swarm on an high-performance cluster of GPUs?

**Comment by Luoyang144** [comment]
Of course not, I am using the HPC provided by the lab.

**Comment by borzunov** [comment]
Feel free to reopen if you meet other issues.
