### ISSUE TITLE
Run petals on Windows

### ISSUE THREAD

**Issue by murilocurti** [bigscience-workshop/petals#288]
I had several servers with gpus to add to petals but all of them runs Windows.

Whn I try to install petals I got this error:

`  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\<USER>\AppData\Local\Temp\pip-install-7o_wt6dv\uvloop_e1dae88adb4e4478949729b513424413\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]`
      
 Is there any plans to support windows machines on both public and private swarms?

**Comment by borzunov** [comment]
Hi @murilocurti,

Petals can run on Windows inside WSL2 and Docker, please see our [FAQ](https://github.com/bigscience-workshop/petals/wiki/FAQ:-Frequently-asked-questions#running-a-server). Many users have run the server on Windows successfully in our Discord.

I'll close this issue for now, but feel free to reopen it or create a new one if you run into any issues while trying to set up Petals on Windows.

**Comment by murilocurti** [comment]
Thank you! @borzunov
