### ISSUE TITLE
How much GPU RAM does num_blocks roughly correspond to?

### ISSUE THREAD

**Issue by icopp** [bigscience-workshop/petals#293]
This argument is given as a way to control RAM usage, but there doesn't seem to be any info given on how much actual RAM will be used for a given number of blocks other than using trial and error.

**Comment by borzunov** [comment]
I've added this to the proper [FAQ section](https://github.com/bigscience-workshop/petals/wiki/FAQ:-Frequently-asked-questions#served-blocks) for now.
