### ISSUE TITLE
Is  (IA)^3 Possible?

### ISSUE THREAD

**Issue by Jeduh** [bigscience-workshop/petals#363]
If so, to what extent? First and last layers maybe??

**Comment by borzunov** [comment]
Hi @Jeduh!

Right now, you can insert any PyTorch operations **between** remote transformer blocks (see Step 5 in the ["Getting started"](https://colab.research.google.com/drive/1uCphNY7gfAUkdDrTx21dZZwCOUDCMPw8?usp=sharing) tutorial) but can't add layers inside a remote block.

You can also host some transformer blocks locally and modify them as you want, while running the rest of the model through the swarm. This is useful, e.g., if you want to add adapters to 10-30% of transformer blocks and leave the rest of the blocks as is.

**Comment by Jeduh** [comment]
Wow, fair system.
Thank you @borzunov :)

Do you know how I could train 65B for longer contexts? I need to train familiarity with interpolated positional embedding scales (NTK, or SRoPE). Anything you I should look up?
