### ISSUE TITLE
colab notebook fails to run CPU and CUDA error

### ISSUE THREAD

**Issue by pleabargain** [bigscience-workshop/petals#375]
I initiated the
```model = AutoDistributedModelForCausalLM.from_pretrained(model_name, active_adapter="timdettmers/guanaco-65b") ```
the notebook before initiating 
```Step 2. Chatbots and interactive```
but I got this error
![image](https://github.com/bigscience-workshop/petals/assets/640846/4ebb8ebe-28fc-4e25-bedb-9921cda30b3c)

**Comment by borzunov** [comment]
Hi @pleabargain,

Just to confirm, does the standard GPU-enabled work for you?

Regarding the CPU-only notebook, just ensure that you don't have `.cuda()` anywhere and it should work. If it doesn't, please share your notebook with `.cuda()` removed everywhere and I'll take a look.

**Comment by borzunov** [comment]
Hi @pleabargain,

Just add `model = model.cuda()` after you create the model, then it should work.

(I've deleted my 1st response since I misunderstood your question at first)

**Comment by pleabargain** [comment]
Thanks! Worked like a charm!
![image](https://github.com/bigscience-workshop/petals/assets/640846/2faf12ba-b2dc-474c-8a5e-4adbb55916f5)
