### ISSUE TITLE
petals doesn't know that there are 31 days in OCT

### ISSUE THREAD

**Issue by pleabargain** [bigscience-workshop/petals#381]
http://chat.petals.ml/
![image](https://github.com/bigscience-workshop/petals/assets/640846/5f73d8b4-a97e-47a1-bd3d-222ef0620466)

**Comment by borzunov** [comment]
Hi @pleabargain,

This is an issue with the LLM you were using. Petals is a system for running different of LLMs, issues of a particular LLM are not relevant to us (we can't do anything about them).
