### ISSUE TITLE
Official website disappear

### ISSUE THREAD

**Issue by edsonke** [bigscience-workshop/petals#386]
Hi everyone,

I'm new to this fascinating project and I'm eager to explore more documents on the official website. Unfortunately, it seems that https://petals.ml/ is currently inaccessible. Could someone please look into this issue and either correct the link or consider removing it from the project since it appears to be missing or unavailable?

Thank you for your attention.

**Comment by borzunov** [comment]
Hi @edsonke,

Thanks for reporting! There's an issue with our domain registrar. If it doesn't resolve soon, we'll switch to a new domain.

**Comment by borzunov** [comment]
If you can't connect to public swarm bootstrap peers, please update to Petals 2.0.0.post2. This version contains bootstrap peer IP addresses for a direct connection without DNS name resolution:

`pip install --upgrade petals`

If you'd like to use a chatbot app or a health service, you can use their IP addresses in your browser (see below) or add this to `/etc/hosts`:

```
185.199.108.153 petals.ml
159.223.29.252 bootstrap1.petals.ml
24.144.96.147 bootstrap2.petals.ml
143.244.175.95 chat.petals.ml
24.144.96.147 health.petals.ml
```

**Comment by borzunov** [comment]
Hi @edsonke,

We've moved to a new domain, see https://petals.dev, https://chat.petals.dev, and https://health.petals.dev

Let us know if you have any other issues!
