### ISSUE TITLE
ERROR: Could not build wheels for grpcio-tools, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by mberman84** [bigscience-workshop/petals#388]
I keep getting this error. I've tried to install different versions of grpcio, using a conda env, different versions of python...anyone else having this issue? I'm on a mac M2.

**Comment by borzunov** [comment]
Hi @mberman84,

This is an issue with Python 3.11 that we don't properly support yet. Please try Python 3.8 - Python 3.10. If you're running from macOS, I'd recommend using our Docker image (see readme) since Petals doesn't work on macOS natively.

**Comment by mberman84** [comment]
@borzunov also, looking at the docker image for MacOS, it looks like that's just to run the server, but what about as a client?

**Comment by borzunov** [comment]
Hi @mberman84,

You'd have to use WSL and/or Docker to run a Petals server or client on Windows. See FAQ for instructions or ask for help in Discord (there are many people who managed to set everything up).

Regarding the client on macOS, you can develop your app **inside** Docker - share some local directories with the container and run `bash` to get access to the terminal inside Docker. Please look up Docker tutorials on how to do that.

**Comment by borzunov** [comment]
Python 3.11 support was fixed in #393.

Regarding WSL, I'll add a better instruction soon.

Let us know if you have any other issues!

**Comment by mberman84** [comment]
Yes, that worked. I'm getting some other errors but will try to work through that. Thank you

**Comment by borzunov** [comment]
@mberman84 Don't hesitate to make an issue if you spend more than 30 min on something :)
