### ISSUE TITLE
Cuda 11.8 supported?

### ISSUE THREAD

**Issue by vadi2** [bigscience-workshop/petals#395]
Cuda 11.8 improves inferencing speed by 2x for rtx 4000 series cards (I've seen it personally with Stable Diffusion and it can be [seen on HN](https://news.ycombinator.com/item?id=36787473)). Can it work for hosting petals as well?

**Comment by Jeduh** [comment]
Yes, I tried it a couple days ago.

**Comment by borzunov** [comment]
Hi @vadi2,

Yes, it should work. I think even CUDA 12.0 now works.
