### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by dinosaurtirex** [bigscience-workshop/petals#400]
I tried to install and got error:
```
RuntimeError: uvloop does not support Windows at the moment
```
You guys making great job, but if you want to engage more people you need to have executable simple programs which is very easy to install on computer, like utorent

**Comment by zerofill** [comment]
They have a dockerfile

**Comment by dinosaurtirex** [comment]
> They have a dockerfile

Yes they have, but do torent users know about docker? If community want to increase power of network they need to simplify product as deep as possible for endpoint user. For me - of course i have and can install this via docker and already did it. But for someone who want to help, may be on mac, or on ordinary windows PC, do they know about docker? i don't think so.

**Comment by phineas-pta** [comment]
it's literally written in the wiki, users need to read first

**Comment by borzunov** [comment]
Hi @dinosaurtirex,

We have 1.75 people maintaining the project and don't have capacity to make everything work on Windows natively (without Docker or WSL), so we won't be able to implement this in the nearest future. We'd be happy if you can help with development of the native Windows version (I'd estimate this is a 1-2 month project).

**Comment by borzunov** [comment]
We'll also add a better instructions for setting up WSL soon (maybe even a video).

**Comment by borzunov** [comment]
@dinosaurtirex Here's the new detailed WSL instruction: https://github.com/bigscience-workshop/petals/wiki/Run-Petals-server-on-Windows

Feel free to reopen this if you have any issues with it!

**Comment by dinosaurtirex** [comment]
> @dinosaurtirex Here's the new detailed WSL instruction: https://github.com/bigscience-workshop/petals/wiki/Run-Petals-server-on-Windows
> 
> Feel free to reopen this if you have any issues with it!

Thank you very much
