### ISSUE TITLE
Remember Chat History

### ISSUE THREAD

**Issue by solo2424** [bigscience-workshop/petals#415]
Is us possible to send your chat history to the llm for follow-up questions? if so, can someone explain how to do this?

**Comment by borzunov** [comment]
Hi @solo2424,

Sure, please take a look at the chatbot example in the ["Getting started" tutorial](https://colab.research.google.com/drive/1uCphNY7gfAUkdDrTx21dZZwCOUDCMPw8?usp=sharing).
