### ISSUE TITLE
Request to Enable Git Discussions Feature

### ISSUE THREAD

**Issue by audioXD** [bigscience-workshop/petals#420]
Hello,

I hope you are doing well. I would like to request the enablement of the ["GitHub Discussions"](https://github.com/features/discussions) feature for this repository. I believe this feature will greatly enhance collaboration and communication among contributors and users.

**Benefits of Git Discussions:**

- Provides a space for general discussions, questions, and announcements related to the project.
- Streamlines communication between maintainers, contributors, and users without cluttering the issue tracker.
- Helps users find answers to frequently asked questions and reduces duplicated support requests.

**Request:**

Could you kindly enable the ["GitHub Discussions"](https://github.com/features/discussions) feature for this repository? I believe it will be beneficial for everyone involved in this open-source project.

Thank you for considering this request.

**Comment by borzunov** [comment]
Hi @audioXD,

Thanks for reaching out!

One concern I have is that we have a very active [Discord community](https://discord.gg/D9MwApKgWa) that serves most of these purposes. Creating a separate discussion space may fragment the existing community, and it'll be more difficult for us to watch both of them for questions/updates.

What do you think about that?

**Comment by audioXD** [comment]
Hi @borzunov,

I agree with your point about the active Discord server, and I must admit that I somewhat skipped noticing it earlier. Nevertheless, I believe we can now take steps to promote it better on GitHub. Creating a pinned issue and enhancing the issue template should help us maintain the active community while utilizing both platforms effectively.

Let me know your thoughts!
