### ISSUE TITLE
Add an example on how decoding algorithm can be used.

### ISSUE THREAD

**Issue by SamAct** [bigscience-workshop/petals#425]
Hi
Just couldn't find an example where decoding_algorithms - GreedyAlgorithm, SamplingAlgorithm, BeamSearchAlgorithm are used. GreedyAlgorithm is by default, the colab notebook promises to discuss it but it seems to miss out on a clear and detailed discussion regarding these specific decoding algorithms.

Could you please share some resource or example code that distinctly demonstrates how to use these decoding algorithms during inference? Any guidance on the pros and cons of each, and under what circumstances one might be favorable over the others, would also be greatly appreciated.

**Comment by SamAct** [comment]
```
from petals.utils.generation_algorithms import (
    BeamSearchAlgorithm,
    DecodingAlgorithm,
    GreedyAlgorithm,
    NucleusAlgorithm,
    SamplingAlgorithm,
    TopKAlgorithm,
)
import torch
from transformers import AutoTokenizer
from petals import AutoDistributedModelForCausalLM

with model.inference_session(max_length=1024) as sess:
    while True:
        prompt = input('Human: ')
        if prompt == "":
            break
        prefix = f"Human: {prompt}\nFriendly AI:"
        prefix = tokenizer(prefix, return_tensors="pt")["input_ids"].cuda()
        print("Friendly AI:", end="", flush=True)

        while True:
            outputs = model.generate(prefix, max_new_tokens=1,decoding_algorithm=BeamSearchAlgorithm(num_beams=1, batch_size=1), session=sess,
                                     do_sample=True, temperature=0.9, top_p=0.6)
            outputs = tokenizer.decode([fake_token, outputs[0, -1].item()])[1:]

            # Now, let's print one new token at a time
            print(outputs, end="", flush=True)

            if "\n" in outputs:
                break
            prefix = None  # Prefix is passed only for the 1st token of the bot's response
```

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when 
checking argument for argument tensors in method wrapper_CUDA_cat)

I am sure my setup is not correct, whats wrong here?

**Comment by SamAct** [comment]
> Hi @SamAct! This page from the Transformers docs should answer your question: https://huggingface.co/docs/transformers/generation_strategies#decoding-strategies

Doesn't help me enough, to implement seems the setups are way different in this regard.

**Comment by SamAct** [comment]
Looking at the code, it seems we can select any of the following just by playing around with top_k, top_p and do_sample paramters. If you have a more direct way let we know

Allowed algos:    ` BeamSearchAlgorithm,    DecodingAlgorithm,    GreedyAlgorithm,    NucleusAlgorithm,    SamplingAlgorithm,    TopKAlgorithm,`
```python
    def _choose_sample_algorithm(
        self,
        temperature: float = 1.0,
        top_k: Optional[int] = None,
        top_p: Optional[float] = None,
    ) -> DecodingAlgorithm:
        if (top_k is not None) and (top_p is not None):
            raise ValueError("You have to provide only top_k or top_p for sampling")
        if top_k is not None:
            return TopKAlgorithm(top_k, temperature)
        elif top_p is not None:
            return NucleusAlgorithm(top_p, temperature)
        else:
            return SamplingAlgorithm(temperature)
```
```python
        if decoding_algorithm is None:
            if do_sample:
                decoding_algorithm = self._choose_sample_algorithm(temperature, top_k, top_p)
            elif num_beams is not None and num_beams > 1:
                decoding_algorithm = BeamSearchAlgorithm(num_beams, batch_size=batch_size)
            else:
                if top_k is not None or top_p is not None:
                    logger.warning("You passed top_k or top_p but did not pass do_sample=True. Running greedy sampling")
                decoding_algorithm = GreedyAlgorithm()
```

**Comment by borzunov** [comment]
Hi @SamAct,

Please note that our custom generation code was [removed](https://github.com/bigscience-workshop/petals/releases/tag/v2.1.0) in Petals 2.1.0, now we use the HF Transformers `.generate()` code directly. This means that most HF `.generate()` options should work correctly now.

Please refer to this page for explanation of most popular algorithms: https://huggingface.co/blog/how-to-generate

Feel free to reopen this issue if you still have any problems with generation via Petals.
