### ISSUE TITLE
Repack StableBeluga2 to small shards + safetensors

### ISSUE THREAD

**Issue by borzunov** [bigscience-workshop/petals#450]
StableBeluga2 standard distribution has issues:

- It uses float32 while we load it in bfloat16 (so we download/read 2x more data than needed).
- It uses huge shards (so the client has to load 2 shards of ~18 GB in total with lots of data it doesn't use).
- It uses pickle serialization (so reading from disk is slower than with Safetensors).

The task is to repack StableBeluga2 in Safetensors, addressing these issues. You need to set `"dht_prefix": "StableDiffusion2-hf"` and `"dtype": "bfloat16"` in `config.json` to make it fit into the existing swarm.

**Comment by tonywang16** [comment]
Converted float32 to bfloat16 and sliced the weight to 1GB each. The total size of all weight is half of the original and format is converted to Safetensors.
Currently uploading to the hub
https://huggingface.co/j879/StableBeluga2-bf16

**Comment by tonywang16** [comment]
Model is fully uploaded. However dht_prefix is not loaded from config.json 

Aug 13 00:01:53.329 [INFO] Running Petals 2.0.1.post2
Aug 13 00:01:53.502 [INFO] Using DHT prefix: **StableBeluga2-bf16-hf**    <------ instead of StableDiffusion2-hf in config.json
Aug 13 00:02:13.810 [INFO] This server is accessible directly

Am I missing something?

**Comment by borzunov** [comment]
Hi @tonywang16,

Thanks for this contribution!

I'll fix the dht prefix issue and loading from safetensors and get back to you.

Would you be okay to move this repo to smth like https://huggingface.co/petals-team/StableBeluga2 ?

**Comment by Jw88888** [comment]
> 

Sure

**Comment by tonywang16** [comment]
Sure

**Comment by borzunov** [comment]
This became a part of the 2.1.0 release: https://github.com/bigscience-workshop/petals/releases/tag/v2.1.0
