### ISSUE TITLE
Add repetition_penalty to RemoteGenerationMixin

### ISSUE THREAD

**Issue by Webifi** [bigscience-workshop/petals#460]
RemoteGenerationMixin / src/petals/client/remote_generation.py doesn't appear to have support for repetition_penalty.  

Is it possible have this added?

**Comment by borzunov** [comment]
Hi @Webifi, I had a branch implementing that, I'll look it up today

**Comment by borzunov** [comment]
Hi @Webifi, I have some old code implementing it: https://github.com/bigscience-workshop/petals/pull/461

I'll update it to be compatible with the latest code and let you know!

**Comment by borzunov** [comment]
The current implementation is not compatible with `top_k` and `top_p` though. We'd like to fix that by introducing a broader compatibility with built-in HF Transformers generation algorithms at some point.

**Comment by borzunov** [comment]
@Webifi I've actually decided to implement a broad compatibility with all the HF `.generate()` options instead (including `repetition_penalty`). Working on it in #464. I'll let you know when it's done and merged.

**Comment by borzunov** [comment]
@Webifi It's done. I've also added support to chat.petals.dev in https://github.com/petals-infra/chat.petals.dev/commit/9e4e06b982e24f190c9fa9fe5f9947b6fc1a98b4.

You can try it out by opening https://chat.petals.dev and trying different values in the JS dev console:

```js
generationParams.repetition_penalty = 0.1; // Always repeat

generationParams.repetition_penalty = 1.2; // Recommended value in the repetition_penalty paper

generationParams.repetition_penalty = 10.0; // Never repeat
```
