### ISSUE TITLE
Python the only option to run?

### ISSUE THREAD

**Issue by arthurwolf** [bigscience-workshop/petals#469]
Do I really need to write/copy-paste/understand python code to try this out, as the getting-started guide seems to indicate?

Is there not some command line tool or web interface that I can use instead?

I'd appreciate any help getting this to work in a straightforward fashion.
Looking forward to sharing my computing ressources, awesome project btw.

**Comment by borzunov** [comment]
Hi @arthurwolf,

You can use the chatbot interface to try the model out without coding: https://chat.petals.dev

If you want to share your GPU, please follow this: https://github.com/bigscience-workshop/petals#connect-your-gpu-and-increase-petals-capacity

Also, you don't have to copy-paste Python code from the "Getting started" guide - you can just run it in Google Colab as is.

Let us know if you have other questions!

**Comment by arthurwolf** [comment]
I tried chat.petals.dev several times since your message, and it always fails to produce any helpful output:

![Screenshot from 2023-08-31 01-12-35](https://github.com/bigscience-workshop/petals/assets/108821/f20c4001-be63-48ff-941d-d0294b1cc7ce)

Any idea what I'm doing wrong?
