### ISSUE TITLE
Add YaLM-100B

### ISSUE THREAD

**Issue by Aspect004** [bigscience-workshop/petals#512]
Could you consider adding the YaLM-100B open-source model by Yandex? I think it would be a nice addition.

**Comment by borzunov** [comment]
Hi @Aspect004,

Unfortunately, our team does not have capacity to work on this. If necessary, you can follow the ["Run a custom model"](https://github.com/bigscience-workshop/petals/wiki/Run-a-custom-model-with-Petals) guide to add YaLM support yourself - you can use [this](https://huggingface.co/BlackSamorez/HuYaLM-100B-fp16) HF Transformers-compatible version (sorry about the name).

Please note that YaLM is an older model and is likely to be inferior to smaller newer models that use Chinchilla scaling laws (such as Llama/Llama 2). For example, see benchmarks on [Russian SuperGlue](https://russiansuperglue.com/leaderboard/2).
