### ISSUE TITLE
Add mistral to chat.petals

### ISSUE THREAD

**Issue by AmgadHasan** [bigscience-workshop/petals#527]
Can you please add one of the finetuned mistral models to the chat service?

It's a very capable model and is a good option for those who want fast responses

**Comment by borzunov** [comment]
Hi @AmgadHasan,

Mistral-7B is a relatively small model that can be run on most consumer GPUs if you load it in 4-bit or 8-bit, so we think it doesn't make sense to add it to Petals (it'll work slower than if you run it locally).

Let us know if you have any other questions.
