### ISSUE TITLE
Is there any plan to support MoE models like Mixtral8×7B?

### ISSUE THREAD

**Issue by arronKler** [bigscience-workshop/petals#548]
Like the title says, do we have any plan or do we have the ability to support MoE models like Mixtral8×7B?

**Comment by mryab** [comment]
Hi! We definitely have the ability to support Mixtral and other MoE models (Hivemind, the library for decentralized DL used by Petals, was initially designed for mixtures-of-experts), but currently the team does not have enough bandwidth to implement them in Petals right away. I might have some time over the holidays to work on it, but if you (or someone else from the community) is willing to contribute that, it will probably be much faster

**Comment by fakerybakery** [comment]
+1

**Comment by gaborkukucska** [comment]
+1

**Comment by frburrue** [comment]
Hello,

I'm trying to implement Mixtral8x7B following this guide: https://github.com/bigscience-workshop/petals/wiki/Run-a-custom-model-with-Petals

I have some doubts when implementing the block.py and model.py files. Could you give me some support?

I would be very interested in contributing to the project.

Thank you.

**Comment by artek0chumak** [comment]
Hello!

We added and merged support for Mixtral models: https://github.com/bigscience-workshop/petals/pull/553.

Just update servers for the new version of the petals.
