### ISSUE TITLE
Reachability issue while connecting to private swarm

### ISSUE THREAD

**Issue by CherukupalleNaveen** [bigscience-workshop/petals#562]
I have run DHT on a VM (not the docker way). When I am connecting the peers, I am able to see it in the monitor but not reachable. Neither they are reachable nor able to inference.

**Comment by mryab** [comment]
Hi @CherukupalleNaveen, did you manage to resolve the issue? :)

**Comment by adnanbaqi** [comment]
@CherukupalleNaveen & @mryab Any updates?
